spring:
  mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hn_db?characterEncoding=utf-8&userSSL=false
    data-password: 123456
    data-username: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 1024MB # 单个文件大小
      max-request-size: 10240MB # 总文件大小（允许存储文件的文件夹大小）


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
    file:
        location: D:/SpringBootCodes/hn_pro/src/main/resources/static/upload